-- MySQL Script generated by MySQL Workbench
-- Sun Apr 27 12:50:10 2014
-- Model: New Model    Version: 1.0
SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema vocealuga
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `vocealuga` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `vocealuga` ;

-- -----------------------------------------------------
-- Table `vocealuga`.`carro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vocealuga`.`carro` ;

CREATE TABLE IF NOT EXISTS `vocealuga`.`carro` (
  `idcarro` INT NOT NULL AUTO_INCREMENT,
  `marca` VARCHAR(45) NOT NULL,
  `cor` VARCHAR(45) NOT NULL,
  `categoria` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NULL,
  `descricao` VARCHAR(100) NULL,
  PRIMARY KEY (`idcarro`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vocealuga`.`marca`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vocealuga`.`marca` ;

CREATE TABLE IF NOT EXISTS `vocealuga`.`marca` (
  `idmarca` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NULL,
  PRIMARY KEY (`idmarca`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vocealuga`.`cor`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vocealuga`.`cor` ;

CREATE TABLE IF NOT EXISTS `vocealuga`.`cor` (
  `idcor` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `vocealuga`.`categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `vocealuga`.`categoria` ;

CREATE TABLE IF NOT EXISTS `vocealuga`.`categoria` (
  `idcategoria` INT UNSIGNED NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`idcategoria`))
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
